import pandas as pd
df = pd.read_csv("data.csv")
print("Original Dataset:")
print(df)
df_clean = df.dropna()
print("\nAfter Removing Missing Values:")
print(df_clean)
df_clean = df_clean.drop_duplicates()
print("\nAfter Removing Duplicates:")
print(df_clean)
avg_temp = df_clean["Temperature"].mean()
avg_humidity = df_clean["Humidity"].mean()
print("\nAverage Temperature:", round(avg_temp, 2))
print("Average Humidity:", round(avg_humidity, 2))